-- Tempo — availability + smart-scheduling preferences
-- Run in your Supabase SQL Editor (after schema.sql). Idempotent — safe to re-run.
--
-- These columns let the smart scheduler place workouts around the user's REAL day:
-- never during sleep, work, or school, biased toward their preferred time of day,
-- and constrained to the days they actually want to train. `schedule_flexibility`
-- controls how aggressively Tempo may move a workout when life gets in the way.
--
-- All columns are optional / defaulted, so the app reads them gracefully and
-- behaves exactly as before when they're empty.

-- ── Availability + scheduling prefs on the user profile ──────────────────────
ALTER TABLE public.user_profiles
  -- Sleep window — workouts are NEVER placed between bedtime and wake_time.
  ADD COLUMN IF NOT EXISTS wake_time time NOT NULL DEFAULT '06:30',
  ADD COLUMN IF NOT EXISTS bedtime   time NOT NULL DEFAULT '22:30',
  -- Recurring daily commitments to schedule around (null = none).
  ADD COLUMN IF NOT EXISTS work_start   time,
  ADD COLUMN IF NOT EXISTS work_end     time,
  ADD COLUMN IF NOT EXISTS school_start time,
  ADD COLUMN IF NOT EXISTS school_end   time,
  -- Soft preference for when to train; the scheduler still varies within it.
  ADD COLUMN IF NOT EXISTS preferred_time_of_day text
    CHECK (preferred_time_of_day IN ('morning','afternoon','evening')),
  -- How freely Tempo may move a workout to keep you on track.
  ADD COLUMN IF NOT EXISTS schedule_flexibility text NOT NULL DEFAULT 'balanced'
    CHECK (schedule_flexibility IN ('strict','balanced','flexible')),
  -- Weekdays the user is willing to train, ISO 1=Mon … 7=Sun. Empty = no limit.
  ADD COLUMN IF NOT EXISTS training_days int[] NOT NULL DEFAULT '{}',
  -- Which calendar new workout events sync to when both are connected.
  ADD COLUMN IF NOT EXISTS preferred_calendar text
    CHECK (preferred_calendar IN ('google','device'));

-- ── Track which calendar a workout's event lives in ──────────────────────────
-- Lets "Remove from Calendar" delete from the right place (Google vs device) and
-- keeps the two systems from clobbering each other's event IDs.
ALTER TABLE public.scheduled_workouts
  ADD COLUMN IF NOT EXISTS calendar_provider text
    CHECK (calendar_provider IN ('google','device'));

-- Where a scheduled workout came from. Lets the Smart Scheduler REPLACE only its
-- own prior auto-scheduled sessions on a re-run (never the user's plan workouts or
-- ad-hoc Quick Workouts), so re-running doesn't clutter the calendar.
--   'plan'  — generated by the 4-week plan builder
--   'quick' — an ad-hoc Quick Workout
--   'smart' — placed by the Smart Scheduler around the user's calendar
ALTER TABLE public.scheduled_workouts
  ADD COLUMN IF NOT EXISTS source text
    CHECK (source IN ('plan','quick','smart'));
