// Tempo — "who made this workout?" labelling.
//
// A Tempo-generated "Push" day and a user's own "Push" day carry the same focus
// label, so the schedule needs to say which is which. The `source` on every
// scheduled workout already encodes it: plan/quick/smart come from Tempo, while
// custom/split are the user's own. One helper keeps that wording consistent across
// the Home feed, the Train hub, history, and My Splits.

import type { WorkoutSource } from '@/types'
import { BRAND_NAME } from '@/constants/brand'

export interface WorkoutOrigin {
  byTempo: boolean
  label: string    // full: "<Brand> plan", "Quick workout", "Your split", "Your workout"
  short: string    // compact chip text: "<Brand>" | "Yours"
  icon: string     // Ionicons name
}

export function workoutOrigin(source: WorkoutSource | null | undefined): WorkoutOrigin {
  switch (source) {
    case 'quick':
      return { byTempo: true, label: 'Quick workout', short: BRAND_NAME, icon: 'flash' }
    case 'smart':
      return { byTempo: true, label: `${BRAND_NAME} scheduled`, short: BRAND_NAME, icon: 'sparkles' }
    case 'split':
      return { byTempo: false, label: 'Your split', short: 'Yours', icon: 'person' }
    case 'custom':
      return { byTempo: false, label: 'Your workout', short: 'Yours', icon: 'person' }
    case 'plan':
    default:
      // Unknown/legacy rows are plan-generated by default.
      return { byTempo: true, label: `${BRAND_NAME} plan`, short: BRAND_NAME, icon: 'sparkles' }
  }
}
